[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# Choose a configuration that suits your project's versioning style
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
# write_to = "src/pyFVDA/_version.py"